### ISSUE TITLE
Transfer to personal account?

### ISSUE THREAD

**Issue by maelle** [robjhyndman/ozbabynames#11]
@robjhyndman et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by robjhyndman** [comment]
I'd be happy to update and maintain this if there are no other takers.

**Comment by maelle** [comment]
@robjhyndman, thank you, I've requested the transfer, please accept it (and others could then ask you for yet another transfer, sorry for the clunkiness)
