### ISSUE TITLE
Link to other babynames packages

### ISSUE THREAD

**Issue by njtierney** [robjhyndman/ozbabynames#8]
- @hadley 's [USA babynames](https://github.com/hadley/babynames)
- @ekothe 's [NZ babynames](https://github.com/ekothe/nzbabynames)
- And more?

It might also be worthwhile to try and make sure we have a similar naming structure to others, so that it can be easy to combine / compare names.

**Comment by ekothe** [comment]
I'm working on New Zealand, France, Norway for the last 100+ years (I've got the underlying data for all of these but France and Norway aren't on github yet). I'm also planning on refactoring nzbabynames to make sure it's consistent with hadley's package (it's not terrible but it the capitalization is a bit iffy).

**Comment by njtierney** [comment]
Nice, @ekothe ! I've heard that you were doing some other countries, this is super great!

**Comment by robjhyndman** [comment]
Added in https://github.com/robjhyndman/ozbabynames/commit/220d498fe562b77f81ef1629eee1806664f1ad22
